### ISSUE TITLE
Ember CLI: ENOENT, no such file or directory ... index.html w/ 1.2.0

### ISSUE THREAD

**Issue by john-kurkowski** [jonathanKingston/broccoli-sri-hash#10]
I get the following trace in my Ember CLI project with broccoli-sri-hash 1.2.0, depended upon by ember-cli-sri. If I manually rollback to broccoli-sri-hash 1.1.1, the problem goes away.

``` zsh
➜ ember test
Future versions of Ember CLI will not support v0.10.40. Please update to Node 0.12 or io.js.
version: 1.13.8
Invalid watchman found, version: [4.1.0] did not satisfy [^3.0.0], falling back to NodeWatcher.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Build failed.
ENOENT, no such file or directory '/path/to/my-cool-app/tmp/srihash_assets-output_path-S8FPzcEu.tmp/my-cool-app/index.html'
Error: ENOENT, no such file or directory '/path/to/my-cool-app/tmp/srihash_assets-output_path-S8FPzcEu.tmp/my-cool-app/index.html'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.writeFileSync (fs.js:978:15)
    at SRIHashAssets.processFile [as processHTMLFile] (/path/to/my-cool-app/node_modules/ember-cli-sri/node_modules/broccoli-sri-hash/index.js:208:6)
    at Array.map (native)
    at SRIHashAssets.build (/path/to/my-cool-app/node_modules/ember-cli-sri/node_modules/broccoli-sri-hash/index.js:228:22)
    at /path/to/my-cool-app/node_modules/ember-cli-sri/node_modules/broccoli-sri-hash/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/path/to/my-cool-app/node_modules/ember-cli-sri/node_modules/broccoli-sri-hash/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/path/to/my-cool-app/node_modules/ember-cli-sri/node_modules/broccoli-sri-hash/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/path/to/my-cool-app/node_modules/ember-cli-sri/node_modules/broccoli-sri-hash/node_modules/rsvp/dist/rsvp.js:476:11)
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/path/to/my-cool-app/node_modules/ember-cli-sri/node_modules/broccoli-sri-hash/node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Comment by blimmer** [comment]
I'm also seeing this error on 1.2.0.

**Comment by ming-codes** [comment]
:+1:

**Comment by stefanpenner** [comment]
@rwjblue im in TC39, do you have cycles to take a look?

**Comment by rwjblue** [comment]
yep, looking

**Comment by rwjblue** [comment]
I just unpublished 1.2.0 while I track down what is going on.
